### ISSUE TITLE
Could you please add address line 2

### ISSUE THREAD

**Issue by Pete1408** [philippnormann/nvidia-sniper#10]
Unfortunately when checking out i need address line 2 in order for the company im reshipping with to my location to know the parcel is allocated to me / my locker kind of thing. If you could add this that would be fricken amazing, many thanks!

**Comment by philippnormann** [comment]
Implemented in https://github.com/philippnormann/nvidia-sniper/commit/b429e7f90d0950f880242904a1cb3d261651230a ✔️
