### ISSUE TITLE
captcha at final submit page

### ISSUE THREAD

**Issue by jaklap** [philippnormann/nvidia-sniper#11]
captcha at final confirm order page, I think this is new? Not sure if it appears to all or only if you've been running for a while - I was monitoring the 3080 for a few hours then ran a 2060S test and saw it at the final step. If you have images disabled the captcha images will not load either.
![unknown](https://user-images.githubusercontent.com/71605989/93917035-6cfee100-fcd8-11ea-91f6-c54249bb9cfb.png)

![unknown (1)](https://user-images.githubusercontent.com/71605989/93917034-6cfee100-fcd8-11ea-9f23-9c843ebe6e76.png)

**Comment by philippnormann** [comment]
@jaklap There it is! There are lots of things we can do about this but for now we always enable image loading and the reCAPTCHA has to be completed manually. Thanks for reporting the issue!
