### ISSUE TITLE
Latest build seems slower 

### ISSUE THREAD

**Issue by soomld** [philippnormann/nvidia-sniper#12]
Howdy,

I've been updating and testing your build daily and today's build seems slower compared to yesterday build. I noticed it during the checking out button process (after adding to cart, before adding personal information). Is it because of the notification send off command before it can proceed to next step? Just wanted to give my feedback. Thanks again!

**Comment by philippnormann** [comment]
Hey @soomld, you are right the addition of all the notifications slowed down the checkout quite a bit. In commit https://github.com/philippnormann/nvidia-sniper/commit/4d9de3298878c7ebed56bdfdc237bc759eb11775 we outsourced the notification sender into a separate thread. This yielded a significant performance improvement. I will therefore close this issue for now. If you see any performance degradation in the future, feel free to open another issue for it.
