### ISSUE TITLE
getting error on run

### ISSUE THREAD

**Issue by Waderaid** [philippnormann/nvidia-sniper#16]
File "c:\users\wader\appdata\local\programs\python\python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 25 column 9 (char 672)

**Comment by LonleyViper** [comment]
check your config files. You left a comma off where you should not have 👍

**Comment by philippnormann** [comment]
@LonleyViper is correct. I added better error messages for this type of issue in https://github.com/philippnormann/nvidia-sniper/commit/5d944ee4b530e4de3d729f103bb313a0059c73e1. I hope that helps other users running into the same problem!

**Comment by Waderaid** [comment]
Thanks< I redid config and now working
