### ISSUE TITLE
No module named 'aiohttp'

### ISSUE THREAD

**Issue by LonleyViper** [philippnormann/nvidia-sniper#17]
Running on mac, getting the following error :(

`  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/<username>/Documents/nvidia-sniper/sniper/__main__.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'`

**Comment by LonleyViper** [comment]
Have tried updating python also. No joy :(

**Comment by LonleyViper** [comment]
SOLVED!

On mac: `$ pipenv run python -m sniper`

Honestly I've never coded with this stuff before...ive only aver used VBA...maybe I should learn xD

**Comment by philippnormann** [comment]
Hey @LonleyViper, installing the project dependencies using `pipenv install` should have also installed `aiohttp`, but I am glad you could resolve your problem using that workaround! :+1:
