### ISSUE TITLE
Issues with Notifications Again

### ISSUE THREAD

**Issue by AnushK-Fro** [philippnormann/nvidia-sniper#24]
Hello,

I am still receiving the same issues with notifications. On my last issue, I had accidentally copied and pasted my JSON wrong. I have verified my JSON with jsonlint and it's valid.

`ERROR:root:Error while parsing the notification configuration file, check config/notifications.json for syntax errors and fix them to continue.`

```
{
    "notifications": {
        "started": {
            "message": "Nvidia Sniper Started! 🕹️",
            "enabled": true
        },
        "availability": {
            "message": "Quick, before it is gone! 🏃‍♂️",
            "enabled": true
        },
        "add-to-basket": {
            "message": "Locked and loaded! 🔫",
            "enabled": true
        },
        "checkout": {
            "message": "Checkout complete! ✅",
            "enabled": true
        },
        "submit": {
            "message": "SNIPED! 🎯",
            "enabled": true
        },
        "captcha-fail": {
            "message": "Failed to CAPTCHA that card! 🤖",
            "enabled": true
        }
    },
    "services": {
        "apprise-1": {
            "url": "discord://INSERT_HERE/INSERT_HERE",
            "screenshot": true
        }
    }
}

**Comment by YolongJohnson** [comment]
change the file names to simply customer and notifications respectively, that should fix this issue.

**Comment by philippnormann** [comment]
This seems like a question that should have been posted in our [discord](https://paypal.me/PhilippNormann) #support channel. 
Please only open issues on this GitHub project for unknown bugs or feature requests in the future :tipping_hand_man:
