### ISSUE TITLE
Blank Screenshots

### ISSUE THREAD

**Issue by YolongJohnson** [philippnormann/nvidia-sniper#28]
Everything seems to be working fine; however, when using notifications is the first screenshot supposed to be blank or is it supposed to be the loading page for that specific GPU? I attached a photo of the image I am receiving. 

![photo_2020-09-28_20-54-31](https://user-images.githubusercontent.com/52083486/94500801-35a79d00-01ce-11eb-9f0b-ff9ad0bbc76e.jpg)

**Comment by Kneely23** [comment]
Its probably because its taking a screenshot as the browser is initially loading the page which is all white for a split second. I tested the bot with a 2060s and it had a blank screenshot at first but the next screenshots as its going through checkout appeared normally.

**Comment by YolongJohnson** [comment]
I tried it with 2060 around about two hours ago when they where up. I got following after it started: 

Started - GeForce RTX 2060 Super
Nvidia Sniper Started! 🕹️

![photo_2020-09-28_20-54-31](https://user-images.githubusercontent.com/52083486/94512114-46194100-01e9-11eb-916f-24e8a71d63fe.jpg)

Availability - GeForce RTX 2060 Super
Quick, before it is gone! 🏃‍♂️

![photo_2020-09-29_00-18-38](https://user-images.githubusercontent.com/52083486/94512145-59c4a780-01e9-11eb-9672-ac5bf61f460e.jpg)

Add To Basket - GeForce RTX 2060 Super
Locked and loaded! 🔫

![photo_2020-09-29_00-19-06](https://user-images.githubusercontent.com/52083486/94512176-6b0db400-01e9-11eb-8563-db249facc81c.jpg)

Checkout - GeForce RTX 2060 Super
Checkout complete! ✅

![photo_2020-09-29_00-20-00](https://user-images.githubusercontent.com/52083486/94512231-87115580-01e9-11eb-9eae-6419a15f882e.jpg)

I suspected that it might be taking the screenshot before the page had buffered; however, that doesn't explain why it wont work second "availability" message. I can confirm that they do show up when added to the basket (As shown above).

**Comment by hwamil** [comment]
I think it's a feature we can sacrifice. Every millisecond counts and I think that slowing down the script to take proper screenshots is not a worthwhile pursuit. If anything, getting rid of all screenshots except payment submission seem pretty trivial in honesty.
