### ISSUE TITLE
API Possible Change

### ISSUE THREAD

**Issue by CajunB** [philippnormann/nvidia-sniper#30]
![Sniperissue](https://user-images.githubusercontent.com/72162347/94726839-6cdb9280-0323-11eb-8b99-c6dc875d4d82.PNG)

Manually have to go elsewhere then complete the checkout.

**Comment by philippnormann** [comment]
This issue was fixed in https://github.com/philippnormann/nvidia-sniper/commit/2176c47c2d427d23884ee65138713ce971b5f317. Thanks for reporting it :+1:

**Comment by CajunB** [comment]
No sir, thank you! You're awesome!
