### ISSUE TITLE
[BUG] Bot crashes after filling out adress and before filling out CC details (de)

### ISSUE THREAD

**Issue by johnconnor2020** [philippnormann/nvidia-sniper#31]
I tested several times with the RTX 2060s which is in stock on the german nvidia store.

It added to cart
entered the Adresse
and then entered the credit card number
but it crashes before filling the expiration date of the CC (its two different dropdown menus)
info stays blank and the bot crashes with this error log:

> Traceback (most recent call last):
>   File "c:\users\johnc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\users\johnc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\JohnC\Documents\GitHub\nvidia-sniper\sniper\__main__.py", line 254, in <module>
>     loop.run_until_complete(main())
>   File "c:\users\johnc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "C:\Users\JohnC\Documents\GitHub\nvidia-sniper\sniper\__main__.py", line 220, in main
>     nvidia.checkout_guest(
>   File "C:\Users\JohnC\Documents\GitHub\nvidia-sniper\sniper\nvidia.py", line 246, in checkout_guest
>     fill_out_form(driver, timeout, customer)
>   File "C:\Users\JohnC\Documents\GitHub\nvidia-sniper\sniper\nvidia.py", line 187, in fill_out_form
>     month_select.select_by_value(customer['credit']['expiration']['month'])
>   File "C:\Users\JohnC\.virtualenvs\nvidia-sniper-EfFatCyt\lib\site-packages\selenium\webdriver\support\select.py", line 87, in select_by_value
>     raise NoSuchElementException("Cannot locate option with value: %s" % value)
> selenium.common.exceptions.NoSuchElementException: Message: Cannot locate option with value: 02

**Comment by philippnormann** [comment]
Hey @johnconnor2020, you need to specify your card expiration month without leading zeroes as seen in the `customer_template.json`. That should fix your issue :wink:

**Comment by philippnormann** [comment]
The latest version (https://github.com/philippnormann/nvidia-sniper/commit/c277d3ec39bd6404d58105154c58bf4182fe9ac7) now allows for both formats and strips the leading zeroes if necessary. I hope this helps! :slightly_smiling_face:
