### ISSUE TITLE
Canada locale in documentation showing en-us instead of en-ca

### ISSUE THREAD

**Issue by bryanmanio** [philippnormann/nvidia-sniper#38]
Just wanted to make sure this was intentional, as when I visit the shop from Canada, the URL is showing https://www.nvidia.com/en-ca/ instead. Should I use `en-ca`, or is `en-us` the correct locale?

**Comment by philippnormann** [comment]
Hey @bryanmanio, thanks for asking! It was actually a mistake in the README which is now corrected in https://github.com/philippnormann/nvidia-sniper/commit/ca20d0eae8d15a09ad5e9bff971903df3fac86d1. However it would have probably worked either way as US and Canada share the store backend systems as seen in `data/locales.json`

    "en-ca": {
        "DRlocale": "en_us",
        "apiCurrency": "USD",
        "region": "us"
    },
    "en-us": {
        "DRlocale": "en_us",
        "apiCurrency": "USD",
        "region": "us"
    },
