### ISSUE TITLE
confusion on paypal

### ISSUE THREAD

**Issue by hwamil** [philippnormann/nvidia-sniper#39]
Sorry, this is more of a question than a raise.

There isn't a config for paypal info so are we simply to log in using the bot window or do I use regular firefox to login and gather cookies?

Also, on run we get to pick auto submit but it says it only works with credit card. This prompt is after choosing guest checkout or paypal checkout so it's a little confusing. As in, will it work if I have a credit card added to my paypal account or am I contradicting the previous parameter?

Thank you very much for writing this. I also wrote one using requests and selenium but your code is much more robust and elegant. Learning a lot from going through it.

**Comment by krcm0209** [comment]
If you choose PayPal, the bot will select PayPal for checkout, but you will need to be present to complete the steps on the PayPal website.

**Comment by hwamil** [comment]
Understood! Thanks
