### ISSUE TITLE
Correct phone number format for US

### ISSUE THREAD

**Issue by randomslap** [philippnormann/nvidia-sniper#41]
I noticed that the customer template json has "-" in the phone number but I was wondering if I will need that for a US phone number. I'm assuming that i will not need a "+" and/or a country code. Thank you!

**Comment by krcm0209** [comment]
Whatever you enter in that field is what will be populated on the Nvidia website during checkout. Therefore, you should enter it as you would on Nvidia's website. As long as your locale is set correctly (ex: `en-us` versus `de-de`) then you should be fine.
