### ISSUE TITLE
da_dk locale

### ISSUE THREAD

**Issue by roseninc** [philippnormann/nvidia-sniper#6]
Hi! I would love to try this, but will it work for the danish locale? It would be awesome of that could work! Cheers

**Comment by roseninc** [comment]
I tried using the en-gb locale as you described in the readme, but I am only allowed to pick the following for shipping, hence it wont work : 
![EUrOsVwnbT](https://user-images.githubusercontent.com/58213968/93804414-8e16f180-fc46-11ea-9e3f-927811953601.png)

**Comment by philippnormann** [comment]
@roseninc Sorry that was a typo, the correct locale for Denmark is `da-dk`. You are probably the first one to test it for Denmark, so if you encounter any other problems during checkout, feel free to open another issue!

**Comment by roseninc** [comment]
Hey @philippnormann . Just tried it with the da-dk locale, and it works! Amazing work!! First program i tried that actually works with the danish store. Do you have a discord or something for future development or similar? :-)
