### ISSUE TITLE
Page not found when using en-ca locale

### ISSUE THREAD

**Issue by Weicocu** [philippnormann/nvidia-sniper#62]
Trying to set up nvidia-sniper using en-ca locale. It goes to https://www.nvidia.com/en-ca/geforce/graphics-cards/30-series/rtx-3080/ which is giving a Page Not Found error. Presumably the correct page is somewhere else for Canadian shoppers...

**Comment by philippnormann** [comment]
Hey @Weicocu, you are right! Apparently Canada is a special case, where the Nvidia store is shared between two locales (`en-us`). I fixed this issue in the latest commit https://github.com/philippnormann/nvidia-sniper/commit/63b9db9888c61ece15371180eac91ffd9213073b. Thanks for reporting the bug :beetle:
