### ISSUE TITLE
Captcha Extension not showing up in browser

### ISSUE THREAD

**Issue by c0derGabe** [philippnormann/nvidia-sniper#66]
Hey Guys,

I downloaded the captcha.xpi file and put in the root of the Nvidia-Sniper directory. (ie user/downloads/nvidia-sniper) but when I ran the Nvidia-Sniper bot and the Firefox browser opened I don't see that the captcha extension is there. Am I doing something wrong?

**Comment by hwamil** [comment]
What does your console say?

And for the future, please use the support channel on sniper Discord for questions related to setting up as opening issues here entails, usually, a more significant problem.

**Comment by c0derGabe** [comment]
<img width="1280" alt="Untitled" src="https://user-images.githubusercontent.com/69219039/95382461-aed27e80-08b7-11eb-987d-6696e158f4f7.png">
Sorry! I didn't realize you guys a discord. Totally my bad. Here is a screenshot of what I see. Let me know if you would rather me hop into discord for this

**Comment by hwamil** [comment]
Okay sniper seems to be running fine. You should make sure that the extension file has the exact name as mentioned in README 
> recaptcha_solver-5.7-fx.xpi

**Comment by c0derGabe** [comment]
works now thanks!
