### ISSUE TITLE
#Closed

### ISSUE THREAD

**Issue by SalamUchiha** [philippnormann/nvidia-sniper#70]
https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/402196/nvidia-store-update-geforce-rtx-3080-and-rtx-3090-/

**Comment by hwamil** [comment]
'tis a sad old day ain't it

**Comment by SalamUchiha** [comment]
Very. I was there for the drop this afternoon but add to cart just wouldnt work no matter what I did

**Comment by SalamUchiha** [comment]
I watched dozens of people come late and get cards in the discord while i was trying to whole time, just to get 1

**Comment by oriddlero** [comment]
Wait, I thought it was just they were making best by the only reseller of Nvidia cards not the only source.  if they are the only source this is very very bad we need our bought to work for Best buy dammit.. Will donate to the cause!!

**Comment by CPYY** [comment]
This sucks i still haven't gotten a single card :(
