### ISSUE TITLE
I get the following error when I try to launch the bot

### ISSUE THREAD

**Issue by Crotchcritter** [philippnormann/nvidia-sniper#75]
When I get to the very last command "pipenv run python -m sniper" I get the following error:

ERROR:root:Could not import all required modules. Please run the following command again:

        pipenv install

I have already done "pipenv install" and it had no issues. I did it again after the error to verify,, and I get "Requirement already satisfied" on every item it runs through.

FYI my coding is very limited, but I am a network admin so I can follow syntax and have ran through it a couple of times to make sure I'm not missing anything. Thoughts?

**Comment by philippnormann** [comment]
Please visit our [Discord support channel](https://discord.gg/rks69fD) for tech support questions. GitHub issues should only be used for bugs or feature requests.
