### ISSUE TITLE
sniper did not trigger when stock was available today in the uk

### ISSUE THREAD

**Issue by Speedy255** [philippnormann/nvidia-sniper#76]
Apparently stock did appear today in the uk with a link to purchase via scan.co.uk

Sniper did not trigger as it was not available on the NV site direct, but Nvidia had a link to scan to purchase.

**Comment by AdmiralJunkie** [comment]
Can confirm, no alert came through. Quite disappointing.

**Comment by philippnormann** [comment]
This is the expected behavior. Since the drop did not happen directly on https://nvidia.com, sniper wasn't supposed to trigger.
