### ISSUE TITLE
Address suggestion

### ISSUE THREAD

**Issue by roseninc** [philippnormann/nvidia-sniper#8]
The danish da-dk locale works perfectly! Was able to test it with a 2060S, however the address suggestion stopped the sniper in its tracks... I think it would be great with some sort of address suggestion bypass. Do you have any discord group for discussing development? :-) Cheers!

**Comment by wessel145** [comment]
I just wanted to address the same , nl-nl locale. I am also interested in further discussion

**Comment by philippnormann** [comment]
Hey @roseninc! Thanks for the suggestion. I don't think this is strictly necesarry as you can test your address before setting up the bot and adjusting the `customer.json` accordingly. Regarding a discord channel, we are currently discussing development and giving support in a channel on [nvidia-snatcher](https://github.com/jef/nvidia-snatcher)'s [discord](https://discord.gg/Cyc7nrz) 
Invite to our channel -> https://discord.gg/S2SUzX
