### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by 21796114** [philippnormann/nvidia-sniper#83]
Hello there . Thanks for your work.
I uploaded the latest updated version. Previously, the page was constantly refreshed in firefox. But in Mozilla Firefox, the page is no longer refreshed. However, it seems that your stock is being controlled in the program. Is it normal ?

**Comment by philippnormann** [comment]
Yes, that's normal :+1: We switched to refreshing the product page (if SKU is unknown) or API in the background to gain some speed. We only use Firefox in the final checkout steps for filling out the forms and submitting the order.
