### ISSUE TITLE
Guide for updating nvidia-sniper

### ISSUE THREAD

**Issue by soomld** [philippnormann/nvidia-sniper#9]
Is there a guide write up available to update nvidia-sniper. Thanks!

**Comment by Agentscreech** [comment]
usually `git pull` will update it if you have cloned the repo.  If you just downloaded it, you'll have to do that again and replace the contents of the folder you were using originally.

**Comment by soomld** [comment]
Thanks!

**Comment by philippnormann** [comment]
Hey @soomld, @Agentscreech is right! `git pull` is usually the way to go. I added a note to the `README.md`.
